name: Android CI with Project Packaging

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
    - name: Build with Gradle Wrapper
      run: ./gradlew build
    - name: Create project zip
      run: |
        zip -qr project.zip . \
          -x '*.git*' \
          -x '*.github*' \
          -x '**/build/*' \
          -x '*.gradle/*' \
          -x '**/.gradle/*' \
          -x '*.jks' \
          -x '*.pepk' \
          -x 'version_map.json'
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts-build
        path: |
          **/build/libs/*.jar
          project.zip
        retention-days: 0

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582
